Walkthrough ck1
College-Kings/College-Kings pull request #453
Opened 2024-06-22 12:36 UTC by Shaun-Bev

2024-06-22 12:38 UTC, Irishgithub commented
LGTM

2024-06-26 15:07 UTC, KiloOscarSix requested changes

2024-06-26 15:07 UTC, KiloOscarSix commented on game/v2/v2.rpy
>              $ reputation.add_point(RepComponent.TROUBLEMAKER)
```suggestion
        "Deny it" (aubrey=(1.0 if reputation() == Reputations.CONFIDENT else -1.0)):
```

2024-06-26 15:13 UTC, KiloOscarSix commented on game/v2/v2.rpy
> +        "Deny it" (penelope=0.0):
Same as aubrey

2024-06-26 15:15 UTC, KiloOscarSix commented on game/v3/v3.rpy
> +            "Approach her" (bro=1.0):
```suggestion
            "Approach her" (evelyn=0.5):
```

If you're playing for Evelyn this is the choice you want to make so I suggest making it a pale green for clarity

2024-06-26 15:47 UTC, KiloOscarSix requested changes

2024-06-26 15:47 UTC, KiloOscarSix commented on game/v4/v4.rpy
> +            "Apologize" :
```suggestion
            "Apologize" (autumn = (0.5 if reputaiton() == Reputations.LOYAL else None)):
```

2024-06-26 15:47 UTC, KiloOscarSix commented on game/v4/v4.rpy
> +            "Buy Penelope a muffin" (boyfriend=1.0) :
```suggestion
            "Buy Penelope a muffin" (penelope=0.5) :
```

2024-06-26 15:47 UTC, KiloOscarSix commented on game/v4/v4.rpy
> +                "Grab her hand" (penelope=0.0):
```suggestion
                "Grab her hand" (boyfriend=1.0):
```
As this choice doesn't really affect your relationship with Penelope I suggest switched it to BF hint

2024-06-26 15:47 UTC, KiloOscarSix commented on game/v4/v4.rpy
> +        "You wanna go bowling?" (boyfriend=0.0, bro=0.0):
iirc bowling is quite an important event for Penelope so i'd change this to `penelope=1.0`

2024-06-26 15:47 UTC, KiloOscarSix commented on game/v4/v4.rpy
> +                "Encourage her" (boyfriend=1.0):
same here with `penelope=1.0`

2024-06-26 15:47 UTC, KiloOscarSix commented on game/v4/v4.rpy
> +        "Amber" (amber=0.0):
```suggestion
        "Amber" (amber=0.5):
```

2024-06-26 15:55 UTC, KiloOscarSix requested changes

2024-06-26 15:55 UTC, KiloOscarSix commented on game/v5/v5.rpy
> +                "Talk to him" (adam=0.0):
Because you can still punch him chosing this choice i'd change the hint to BF
```suggestion
                "Talk to him" (boyfriend=1.0):
```

2024-11-12 20:34 UTC, merged